/* Copyright (c) 2023 The Brave Authors. All rights reserved.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at https://mozilla.org/MPL/2.0/. */

export const termsOfServiceURL = 'https://basicattentiontoken.org/user-terms-of-service'
export const privacyPolicyURL = 'https://kahfbrowser.com/?privacy/#rewards'
export const settingsURL = 'chrome://rewards'
export const connectURL = 'chrome://rewards/#verify'
export const resetURL = 'chrome://rewards/#reset'
export const reconnectURL = 'chrome://rewards/reconnect'
export const payoutStatusURL = 'https://kahfbrowser.com/?payout-status'
export const tippingLearnMoreURL = 'https://kahfbrowser.com/'
export const contactSupportURL = 'https://community.brave.com/'
export const supportedWalletRegionsURL = 'https://kahfbrowser.com/'
export const aboutBATURL = 'https://kahfbrowser.com/?rewards'
export const rewardsChangesURL = 'https://kahfbrowser.com/?rewards-changes'
export const rewardsTourURL = 'https://kahfbrowser.com/'
export const creatorsURL = 'https://creators.brave.com/'
export const selfCustodyLearnMoreURL = 'https://kahfbrowser.com/?web3/self-custody-wallet/#the-difference-between-custodial-and-non-custodial-wallets'
export const walletCreationDisabledURL = 'https://kahfbrowser.com/?9312922941069'
export const resetSupportURL = 'https://kahfbrowser.com/?10007969237901'
export const helpURL = 'https://kahfbrowser.com/?hc/en-us/categories/360001053052-Rewards'
export const flaggedWalletURL = 'https://kahfbrowser.com/?4494596374925'
export const mismatchedCountriesURL = 'https://kahfbrowser.com/?9809690466061'
export const mismatchedProviderAccountsURL = 'https://kahfbrowser.com/?360034841711-What-is-a-verified-wallet-'
export const braveStatusURL = 'https://status.brave.com/'
export const adsLearnMoreURL = 'https://kahfbrowser.com/?360026361072-Brave-Ads-FAQ'
export const braveSearchURL = 'https://search.brave.com'
export const braveStoreURL = 'https://store.brave.com'
export const wdpLearnMoreURL = 'https://kahfbrowser.com/?privacy/browser/#web-discovery-project'
